const exampleClericData = {
  
  "classLevel": "Cleric 1",
  "background": "Acolyte",
  "playerName": "Your Name",
  "characterName": "Brother Theron",
  "race": "Human", 
  "alignment": "Lawful Good",
  "xp": "0",
  "inspiration": "", 
  "str": "14",
  "profBonus": "+2",
  "ac": "16", 
  "initiative": "+0",
  "speed": "30",
  "personalityTraits": "I idolize a particular hero of my faith and constantly refer to that person's deeds and example.\nI can find common ground between the fiercest enemies, empathizing with them and always working toward peace.",
  "strMod": "+2",
  "hpMax": "10", 
  "stStrength": "+2", 
  "dex": "10",
  "hpCurrent": "10",
  "ideals": "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)",
  "dexMod": "+0",
  "hpTemp": "",
  "bonds": "I will do anything to protect the temple where I served.",
  "con": "15",
  "hdTotal": "1d8",
  "deathSaveSuccess1": false,
  "deathSaveSuccess2": false,
  "deathSaveSuccess3": false,
  "conMod": "+2",
  "deathSaveFailure1": false,
  "deathSaveFailure2": false,
  "deathSaveFailure3": false,
  "hd": "1d8",
  "flaws": "I judge others harshly, and myself even more severely.",
  "int": "12",
  "stDexterity": "+0", 
  "stConstitution": "+4", 
  "stIntelligence": "+1", 
  "stWisdom": "+5", 
  "stCharisma": "+3", 
  "acrobatics": "0", 
  "animalHandling": "+3", 
  "athletics": "+2", 
  "deception": "+1", 
  "history": "+1", 
  "insight": "+5", 
  "intimidation": "+1", 
  "stStrengthProf": false,
  "stDexterityProf": false,
  "stConstitutionProf": true, 
  "stIntelligenceProf": false,
  "stWisdomProf": true, 
  "stCharismaProf": true, 
  "wpnName1": "Mace",
  "wpnAtkBonus1": "+4", 
  "wpnDamage1": "1d6+2 Bludgeoning",
  "intMod": "+1",
  "wpnName2": "Light Crossbow",
  "wpnAtkBonus2": "+2", 
  "wpnDamage2": "1d8 Piercing",
  "investigation": "+1", 
  "wis": "16",
  "wpnName3": "",
  "wpnAtkBonus3": "",
  "arcana": "+1", 
  "wpnDamage3": "",
  "perception": "+3", 
  "wisMod": "+3",
  "cha": "13",
  "nature": "+1", 
  "performance": "+1", 
  "medicine": "+5", 
  "religion": "+3", 
  "stealth": "+0", 
  "acrobaticsProf": false,
  "animalHandlingProf": false,
  "arcanaProf": false,
  "athleticsProf": false,
  "deceptionProf": false,
  "historyProf": false,
  "insightProf": true, 
  "intimidationProf": false,
  "investigationProf": false,
  "medicineProf": true, 
  "natureProf": false,
  "perceptionProf": false,
  "performanceProf": false,
  "persuasionProf": false,
  "religionProf": true, 
  "sleightOfHandProf": false,
  "stealthProf": false,
  "survivalProf": false,
  "persuasion": "+1", 
  "sleightOfHand": "+0", 
  "chaMod": "+1",
  "survival": "+3", 
  "attacksSpellcasting": "Mace: +4 to hit, 1d6+2 bludgeoning damage.\nLight Crossbow: +2 to hit, 1d8 piercing damage.\nSpells: Spell Save DC 13, +5 to hit with spell attacks.",
  "passiveWisdom": "13", 
  "cp": "0",
  "proficienciesLang": "Armor: All armor, shields\nWeapons: Simple weapons\nTools: None\n\nLanguages: Common, Celestial, Dwarvish\n\nProficiencies: Insight, Religion, Medicine",
  "sp": "0",
  "ep": "0",
  "gp": "15", 
  "pp": "0",
  "equipment": "Mace\nChain mail\nShield\nLight crossbow", 
  "featuresTraits": "Spellcasting (Cleric)\nDivine Domain (Life Domain)\nBonus Proficiency (Heavy Armor)\nDisciple of Life\nShelter of the Faithful (Acolyte Feature)",

  
  "characterName2": "Brother Theron", 
  "age": "30",
  "height": "6'0\"",
  "weight": "180 lbs",
  "eyes": "Brown",
  "skin": "Fair",
  "hair": "Black",
  "factionSymbolImage": "", 
  "allies": "The Church of Torm\nFellow Acolytes",
  "factionName": "Church of Torm",
  "backstory": "Theron grew up in the temple, dedicated to the service of Torm, the god of courage and self-sacrifice. He strives to embody his deity's tenets and protect the weak.",
  "featTraits2": "Additional Feats & Traits can go here.", 
  "treasure": "Any found treasure listed here.",
  "characterImage": "", 

  
  "spellcastingClass": "Cleric",
  "spellcastingAbility": "Wisdom",
  "spellSaveDC": "13", 
  "spellAtkBonus": "+5", 

  
  "spellCantrip1": "Guidance",
  "spellCantrip2": "Sacred Flame",
  "spellCantrip3": "Light",
  "spellCantrip4": "",
  "spellCantrip5": "",
  "spellCantrip6": "",
  "spellCantrip7": "",
  "spellCantrip8": "",
  

  
  
  "slotsTotal1": "2",
  "slotsRemaining1": "2",
  "spellLevel1_1": "Bless (Domain)", 
  "spellLevel1_2": "Cure Wounds (Domain)", 
  "spellLevel1_3": "Healing Word", 
  "spellLevel1_4": "Shield of Faith", 
  "spellLevel1_5": "Guiding Bolt", 
  "spellLevel1_6": "Sanctuary", 
  "spellLevel1_7": "",
  "spellLevel1_8": "",
  "spellLevel1_9": "",
  "spellLevel1_10": "",
  "spellLevel1_11": "",
  "spellLevel1_12": "",
  "spellPreparedLevel1_1": true, 
  "spellPreparedLevel1_2": true, 
  "spellPreparedLevel1_3": true,
  "spellPreparedLevel1_4": true,
  "spellPreparedLevel1_5": true,
  "spellPreparedLevel1_6": true,
};



